name: ci
on:
  push:
    branches: ["*"]
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: check vars
        run: |
          echo "AZURE_CLIENT_ID: $AZURE_CLIENT_ID"
          echo "AZURE_TENANT_ID: $AZURE_TENANT_ID"
          echo "AZURE_SUBSCRIPTION_ID: $AZURE_SUBSCRIPTION_ID"

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build And push
        run: |
          az acr login --name buapps.azurecr.io
          docker buildx build -t buapps.azurecr.io/demo-app/hello-word-py:test-ci --push .

      # - name: ACR build
      #   uses: azure/acr-build@v1
      #   with:
      #     registry: buapps.azurecr.io
      #     repository: demo-app
      #     image: hello-word-py
      #     tag: test-ci
