name: 'main flow'

on:
  push:
    branches:
      - master

jobs:
  simple-job: # just a job name
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: file check
        run: ls -la

  call-flow1-job-1:
    uses: ./.github/workflows/flow1.yml@master
