name: 'main flow'

on:
  push:
    branches:
      - master

jobs:
  # simple-job: # just a job name
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2

  #     - name: file check
  #       run: ls -la

  call-flow1-job-1:
    uses: ./.github/workflows/flow1.yml
    # steps is not allowed in a workflow_call job

  call-flow2-job-2:
    needs: call-flow1-job-1
    uses: ./.github/workflows/flow2.yml

  wait-for-test:
    runs-on: ubuntu-latest
    needs:
      - call-flow1-job-1
      - call-flow2-job-2
    steps:
      - name: Check Only call-flow1-job-1
        if: '${{ jobs.call-flow1-job-1.status == "success" && jobs.call-flow2-job-2.status != "success" }}'
        run: echo "Only call-flow1-job-1 succeeded"

      - name: Check Only call-flow2-job-2
        if: '${{ jobs.call-flow1-job-1.status != "success" && jobs.call-flow2-job-2.status == "success" }}'
        run: echo "Only call-flow2-job-2 succeeded"

      - name: Check All
        if: '${{ jobs.call-flow1-job-1.status == "success" && jobs.call-flow2-job-2.status == "success" }}'
        run: echo "All jobs are done"
