name: 'main flow'

on:
  push:
    branchs:
      - master

jobs:
  call-flow1-job-1: # just a job name
    runs-on: ubuntu-latest
    steps:
      - name: try call flow1
        uses: ./flow1.yml@master
